name: Hello
on: push # イベント
# on: [push, pull_request]

jobs:
  hello: # Job Id
    runs-on: ubuntu-latest
    steps:
      - name: Hello World
        run: echo "Hello World!"
      - uses: actions/checkout@v4
