name: Secret
on: push
jobs:
  run:
    runs-on: ubuntu-latest
    env:
      SECRET_KEY: ${{ secrets.SECRET_KEY }}
    steps:
      - run: echo "${SECRET_KEY}"
      - run: echo "${SECRET_KEY:0:1} ${SECRET_KEY#?}"
